### ISSUE TITLE
Fix github action workflows for PRs from external people

### ISSUE THREAD

**Issue by Soneji** [wdhg/mobius#5]
Fix github action workflows for PRs

```yml
if: github.event_name != 'pull_request'
## then run the deploy step
```
I think you just add this `if` under the `step: person/deploy@x`

https://stackoverflow.com/a/66206183
https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions

**Comment by wdhg** [comment]
I added the line to the workflow but the test PR build is still running the deploy step. Is it using the workflow file in your PR?

**Comment by Soneji** [comment]
Yup rerunning the workflow still uses the same old yaml file, just merged main into my patch, should work now 🤞
